// components/marketplace-page.tsx
"use client"

import { useState, useMemo, useEffect } from "react"
import { ChevronLeft, Search, Heart, Plus, X } from "lucide-react"

interface MarketplacePageProps {
  onBack: () => void
  showPublishModal?: boolean
}

const categories = [
  { label: "全部", value: "all" },
  { label: "数码", value: "digital" },
  { label: "书籍", value: "books" },
  { label: "服饰", value: "clothes" },
]

const products = [
  {
    id: 1,
    title: "iPad Pro 11英寸 2021款",
    price: 3200,
    originalPrice: 6799,
    category: "digital",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    likes: 128,
    publisher: {
      name: "张三",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    },
  },
  {
    id: 2,
    title: "人类简史三部曲套装",
    price: 45,
    originalPrice: 168,
    category: "books",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop",
    likes: 86,
    publisher: {
      name: "李四",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    },
  },
  {
    id: 3,
    title: "优衣库轻羽绒服 M码",
    price: 120,
    originalPrice: 499,
    category: "clothes",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop",
    likes: 52,
    publisher: {
      name: "王五",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    },
  },
  {
    id: 4,
    title: "索尼 WH-1000XM4 降噪耳机",
    price: 980,
    originalPrice: 2499,
    category: "digital",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    likes: 234,
    publisher: {
      name: "赵六",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    },
  },
  {
    id: 5,
    title: "米家台灯 Pro",
    price: 85,
    originalPrice: 199,
    category: "digital",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop",
    likes: 67,
    publisher: {
      name: "孙七",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
    },
  },
  {
    id: 6,
    title: "樱桃轴机械键盘",
    price: 280,
    originalPrice: 599,
    category: "digital",
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop",
    likes: 156,
    publisher: {
      name: "周八",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    },
  },
]

export function MarketplacePage({ onBack, showPublishModal: externalShowPublishModal }: MarketplacePageProps) {
  const [searchQuery, setSearchQuery] = useState("")
  const [activeCategory, setActiveCategory] = useState("all")
  const [showPublishModal, setShowPublishModal] = useState(externalShowPublishModal || false)
  const [productForm, setProductForm] = useState({
    title: "",
    description: "",
    price: "",
    originalPrice: "",
    category: "digital",
    condition: "good",
    donationPercentage: 10
  })
  const [isPublishing, setIsPublishing] = useState(false)

  useEffect(() => {
    if (externalShowPublishModal !== undefined) {
      setShowPublishModal(externalShowPublishModal)
    }
  }, [externalShowPublishModal])

  const filteredProducts = useMemo(() => {
    return products
      .filter((p) => activeCategory === "all" || p.category === activeCategory)
      .filter((p) => p.title.toLowerCase().includes(searchQuery.toLowerCase()))
  }, [activeCategory, searchQuery])

  return (
    <section className="max-w-5xl mx-auto px-6 py-8">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <button
            onClick={onBack}
            className="text-sm mb-4 flex items-center gap-1 text-muted-foreground hover:text-foreground transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
            返回
          </button>
          <h1 className="text-2xl font-semibold mb-2 font-serif" style={{ color: "var(--teal-700)" }}>
            益起·流转
          </h1>
          <p className="text-sm text-muted-foreground">闲置物品循环，让爱意在校园流动</p>
        </div>
        <button
          onClick={() => setShowPublishModal(true)}
          className="flex items-center gap-2 px-4 py-2 rounded-full text-white text-sm font-medium transition-all hover:opacity-90"
          style={{ backgroundColor: "var(--teal-600)" }}
        >
          <Plus className="w-4 h-4" />
          发布物品
        </button>
      </div>

      <div className="flex items-center gap-4 mb-8">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="搜索物品..."
            className="w-full pl-9 h-10 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20"
            style={{ backgroundColor: "var(--card)", border: "1px solid var(--border)" }}
          />
        </div>
        <div className="flex items-center gap-2">
          {categories.map((cat) => (
            <button
              key={cat.value}
              onClick={() => setActiveCategory(cat.value)}
              className="px-3 py-1.5 text-sm rounded-lg transition-all"
              style={
                activeCategory === cat.value
                  ? { backgroundColor: "var(--teal-600)", color: "white" }
                  : { backgroundColor: "var(--muted)", color: "var(--muted-foreground)" }
              }
            >
              {cat.label}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-5">
        {filteredProducts.map((product) => (
          <div
            key={product.id}
            className="group rounded-xl overflow-hidden transition-all duration-200 hover:border-teal-300"
            style={{ backgroundColor: "var(--card)", border: "1px solid var(--border)" }}
          >
            <div className="relative aspect-square overflow-hidden" style={{ backgroundColor: "var(--muted)" }}>
              <img
                src={product.image || "/placeholder.svg"}
                alt={product.title}
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div
                className="absolute top-2 right-2 px-2 py-1 rounded text-xs font-medium text-white"
                style={{ backgroundColor: "var(--teal-600)" }}
              >
                公益
              </div>
            </div>
            <div className="p-4">
              <h3 className="text-sm font-medium mb-2 line-clamp-1 text-foreground">{product.title}</h3>
              <div className="flex items-baseline gap-2 mb-3">
                <span className="text-lg font-semibold" style={{ color: "var(--teal-700)" }}>
                  ¥{product.price}
                </span>
                {product.originalPrice && (
                  <span className="text-xs line-through text-muted-foreground">¥{product.originalPrice}</span>
                )}
              </div>
              <div className="flex items-center justify-between pt-3" style={{ borderTop: "1px solid var(--border)" }}>
                <div className="flex items-center gap-2">
                  <img
                    src={product.publisher.avatar || "/placeholder.svg"}
                    alt={product.publisher.name}
                    className="w-5 h-5 rounded-full object-cover"
                  />
                  <span className="text-xs text-muted-foreground">{product.publisher.name}</span>
                </div>
                <div className="flex items-center gap-1 text-xs text-muted-foreground">
                  <Heart className="w-3.5 h-3.5" />
                  <span>{product.likes}</span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {showPublishModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div
            className="absolute inset-0 backdrop-blur-sm"
            style={{ backgroundColor: "rgba(45, 42, 38, 0.2)" }}
            onClick={() => setShowPublishModal(false)}
          />
          <div
            className="relative w-full max-w-lg mx-4 rounded-xl shadow-2xl p-6"
            style={{ backgroundColor: "var(--card)", border: "1px solid var(--border)" }}
          >
            <button
              onClick={() => setShowPublishModal(false)}
              className="absolute top-4 right-4 p-1 rounded-lg text-muted-foreground hover:text-foreground transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
            <div className="mb-6">
              <h2 className="text-xl font-semibold mb-2 font-serif text-foreground">发布闲置物品</h2>
              <p className="text-sm text-muted-foreground">让闲置物品流转起来，传递校园温暖</p>
            </div>
            <form
              onSubmit={(e) => {
                e.preventDefault()
                setIsPublishing(true)
                setTimeout(() => {
                  setIsPublishing(false)
                  setShowPublishModal(false)
                  alert('物品发布成功！')
                  setProductForm({
                    title: "",
                    description: "",
                    price: "",
                    originalPrice: "",
                    category: "digital",
                    condition: "good",
                    donationPercentage: 10
                  })
                }, 1000)
              }}
              className="space-y-4"
            >
              <div className="space-y-2">
                <label className="text-sm font-medium text-foreground">物品标题</label>
                <input
                  type="text"
                  value={productForm.title}
                  onChange={(e) => setProductForm({ ...productForm, title: e.target.value })}
                  placeholder="请输入物品标题"
                  className="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                  style={{ backgroundColor: "var(--background)", border: "1px solid var(--border)" }}
                  required
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium text-foreground">物品描述</label>
                <textarea
                  value={productForm.description}
                  onChange={(e) => setProductForm({ ...productForm, description: e.target.value })}
                  placeholder="请输入物品描述"
                  rows="3"
                  className="w-full rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4 py-3"
                  style={{ backgroundColor: "var(--background)", border: "1px solid var(--border)" }}
                  required
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">价格（元）</label>
                  <input
                    type="number"
                    value={productForm.price}
                    onChange={(e) => setProductForm({ ...productForm, price: e.target.value })}
                    placeholder="0"
                    className="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                    style={{ backgroundColor: "var(--background)", border: "1px solid var(--border)" }}
                    required
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">原价（元）</label>
                  <input
                    type="number"
                    value={productForm.originalPrice}
                    onChange={(e) => setProductForm({ ...productForm, originalPrice: e.target.value })}
                    placeholder="可选"
                    className="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                    style={{ backgroundColor: "var(--background)", border: "1px solid var(--border)" }}
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">物品分类</label>
                  <select
                    value={productForm.category}
                    onChange={(e) => setProductForm({ ...productForm, category: e.target.value })}
                    className="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                    style={{ backgroundColor: "var(--background)", border: "1px solid var(--border)" }}
                  >
                    <option value="digital">数码</option>
                    <option value="books">书籍</option>
                    <option value="clothes">服饰</option>
                    <option value="electronics">电子产品</option>
                    <option value="furniture">家具</option>
                    <option value="daily">日用品</option>
                    <option value="other">其它</option>
                  </select>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">商品成色</label>
                  <select
                    value={productForm.condition}
                    onChange={(e) => setProductForm({ ...productForm, condition: e.target.value })}
                    className="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                    style={{ backgroundColor: "var(--background)", border: "1px solid var(--border)" }}
                  >
                    <option value="brand_new">全新</option>
                    <option value="like_new">几乎全新</option>
                    <option value="good">良好</option>
                    <option value="fair">一般</option>
                    <option value="poor">较差</option>
                  </select>
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium text-foreground">公益捐赠比例（%）</label>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    value={productForm.donationPercentage}
                    onChange={(e) => setProductForm({ ...productForm, donationPercentage: parseInt(e.target.value) })}
                    min="0"
                    max="100"
                    step="5"
                    className="flex-1"
                  />
                  <span className="text-sm font-medium text-foreground w-12 text-right">
                    {productForm.donationPercentage}%
                  </span>
                </div>
              </div>
              <button
                type="submit"
                disabled={isPublishing}
                className="w-full text-white text-sm font-medium py-3 rounded-xl transition-all hover:opacity-90 disabled:opacity-50"
                style={{ backgroundColor: "var(--teal-600)" }}
              >
                {isPublishing ? '发布中...' : '发布物品'}
              </button>
            </form>
          </div>
        </div>
      )}
    </section>
  )
}

// src/components/MarketplacePage.vue
<template>
  <section class="max-w-5xl mx-auto px-6 py-8">
    <div class="mb-8">
      <router-link
        to="/"
        class="text-sm mb-4 flex items-center gap-1 text-muted-foreground hover:text-foreground transition-colors"
      >
        <ChevronLeft class="w-4 h-4" />
        返回
      </router-link>
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-semibold mb-2 font-serif" :style="{ color: 'var(--teal-700)' }">
            益起·流转
          </h1>
          <p class="text-sm text-muted-foreground">闲置物品循环，让爱意在校园流动</p>
        </div>
        <button
          v-if="user"
          @click="showPublishModal = true"
          class="flex items-center gap-2 px-4 py-2 rounded-full text-white text-sm font-medium transition-all hover:opacity-90"
          :style="{ backgroundColor: 'var(--teal-600)' }"
        >
          <Plus class="w-4 h-4" />
          发布物品
        </button>
      </div>
    </div>

    <div class="flex items-center gap-4 mb-8">
      <div class="relative flex-1 max-w-sm">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
        <input
          type="text"
          v-model="searchQuery"
          placeholder="搜索物品..."
          class="w-full pl-9 h-10 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20"
          :style="{ backgroundColor: 'var(--card)', border: '1px solid var(--border)' }"
        />
      </div>
      <div class="flex items-center gap-2">
        <button
          v-for="cat in categories"
          :key="cat.value"
          @click="activeCategory = cat.value"
          class="px-3 py-1.5 text-sm rounded-lg transition-all"
          :style="activeCategory === cat.value 
            ? { backgroundColor: 'var(--teal-600)', color: 'white' } 
            : { backgroundColor: 'var(--muted)', color: 'var(--muted-foreground)' }"
        >
          {{ cat.label }}
        </button>
      </div>
    </div>

    <div class="grid grid-cols-2 md:grid-cols-3 gap-5">
      <div
        v-for="product in filteredProducts"
        :key="product.id"
        class="group rounded-xl overflow-hidden transition-all duration-200 hover:border-teal-300 cursor-pointer"
        :style="{ backgroundColor: 'var(--card)', border: '1px solid var(--border)' }"
        @click="showProductDetail(product)"
      >
        <div class="relative aspect-square overflow-hidden" :style="{ backgroundColor: 'var(--muted)' }">
          <img
            :src="product.image"
            :alt="product.title"
            class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
          />
          <div
            v-if="product.donationPercentage > 0"
            class="absolute top-2 right-2 px-2 py-1 rounded text-xs font-medium text-white"
            :style="{ backgroundColor: 'var(--teal-600)' }"
          >
            公益 {{ product.donationPercentage }}%
          </div>
          <div
            v-if="product.condition"
            class="absolute top-2 left-2 px-2 py-1 rounded text-xs font-medium text-white"
            :style="{ backgroundColor: 'var(--teal-500)' }"
          >
            {{ getConditionLabel(product.condition) }}
          </div>
          <button
            @click.stop="toggleFavorite(product)"
            class="absolute bottom-2 right-2 p-2 rounded-full transition-all hover:scale-110"
            :style="{ backgroundColor: 'rgba(255, 255, 255, 0.9)' }"
          >
            <Heart
              class="w-5 h-5"
              :class="isFavorited(product.id) ? 'fill-red-500 text-red-500' : 'text-gray-600'"
              :fill="isFavorited(product.id) ? 'currentColor' : 'none'"
            />
          </button>
        </div>
        <div class="p-4">
          <h3 class="text-sm font-medium mb-2 line-clamp-1 text-foreground">{{ product.title }}</h3>
          <div class="flex items-baseline gap-2 mb-3">
            <span class="text-lg font-semibold" :style="{ color: 'var(--teal-700)' }">
              ¥{{ product.price }}
            </span>
            <span v-if="product.originalPrice" class="text-xs line-through text-muted-foreground">
              ¥{{ product.originalPrice }}
            </span>
          </div>
          <div class="flex items-center justify-between pt-3" :style="{ borderTop: '1px solid var(--border)' }">
            <div class="flex items-center gap-2">
              <img
                :src="product.publisher.avatar"
                :alt="product.publisher.name"
                class="w-5 h-5 rounded-full object-cover"
              />
              <span class="text-xs text-muted-foreground">{{ product.publisher.name }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Publish Product Modal -->
    <div v-if="showPublishModal" class="fixed inset-0 z-50 flex items-center justify-center">
      <div
        class="absolute inset-0 backdrop-blur-sm"
        :style="{ backgroundColor: 'rgba(45, 42, 38, 0.2)' }"
        @click="showPublishModal = false"
      />
      <div
        class="relative w-full max-w-lg mx-4 rounded-xl shadow-2xl max-h-[90vh] overflow-y-auto"
        :style="{ backgroundColor: 'var(--card)', border: '1px solid var(--border)' }"
      >
        <button
          @click="showPublishModal = false"
          class="absolute top-4 right-4 p-1 rounded-lg text-muted-foreground hover:text-foreground transition-colors"
        >
          <X class="w-5 h-5" />
        </button>
        <div class="p-8">
          <h2 class="text-xl font-semibold mb-2 font-serif text-foreground">{{ productForm.id ? '编辑商品' : '发布闲置物品' }}</h2>
          <p class="text-sm text-muted-foreground mb-6">{{ productForm.id ? '修改商品信息' : '让闲置物品流转起来，传递校园温暖' }}</p>
          
          <form @submit.prevent="handlePublish" class="space-y-4">
            <div class="space-y-2">
              <label class="text-sm font-medium text-foreground">物品标题</label>
              <input
                type="text"
                v-model="productForm.title"
                placeholder="请输入物品标题"
                class="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                :style="{ backgroundColor: 'var(--background)', border: '1px solid var(--border)' }"
              />
            </div>

            <div class="space-y-2">
              <label class="text-sm font-medium text-foreground">物品描述</label>
              <textarea
                v-model="productForm.description"
                placeholder="请输入物品描述"
                rows="3"
                class="w-full rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4 py-3"
                :style="{ backgroundColor: 'var(--background)', border: '1px solid var(--border)' }"
              />
            </div>

            <div class="grid grid-cols-2 gap-4">
              <div class="space-y-2">
                <label class="text-sm font-medium text-foreground">价格（元）</label>
                <input
                  type="number"
                  v-model="productForm.price"
                  placeholder="0"
                  class="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                  :style="{ backgroundColor: 'var(--background)', border: '1px solid var(--border)' }"
                />
              </div>
              <div class="space-y-2">
                <label class="text-sm font-medium text-foreground">原价（元）</label>
                <input
                  type="number"
                  v-model="productForm.originalPrice"
                  placeholder="可选"
                  class="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                  :style="{ backgroundColor: 'var(--background)', border: '1px solid var(--border)' }"
                />
              </div>
            </div>

            <div class="space-y-2">
              <label class="text-sm font-medium text-foreground">物品分类</label>
              <select
                v-model="productForm.category"
                class="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                :style="{ backgroundColor: 'var(--background)', border: '1px solid var(--border)' }"
              >
                <option value="digital">数码</option>
                <option value="books">书籍</option>
                <option value="clothes">服饰</option>
                <option value="electronics">电子产品</option>
                <option value="furniture">家具</option>
                <option value="daily">日用品</option>
                <option value="other">其它</option>
              </select>
            </div>

            <div class="space-y-2">
              <label class="text-sm font-medium text-foreground">商品成色</label>
              <select
                v-model="productForm.condition"
                class="w-full h-11 rounded-xl outline-none focus:ring-2 focus:ring-teal-500/20 px-4"
                :style="{ backgroundColor: 'var(--background)', border: '1px solid var(--border)' }"
              >
                <option value="brand_new">全新</option>
                <option value="like_new">几乎全新</option>
                <option value="good">良好</option>
                <option value="fair">一般</option>
                <option value="poor">较差</option>
              </select>
            </div>

            <div class="space-y-2">
              <label class="text-sm font-medium text-foreground">公益捐赠比例（%）</label>
              <div class="flex items-center gap-3">
                <input
                  type="range"
                  v-model="productForm.donationPercentage"
                  min="0"
                  max="100"
                  step="5"
                  class="flex-1"
                />
                <span class="text-sm font-medium w-12 text-right">{{ productForm.donationPercentage }}%</span>
              </div>
              <p class="text-xs text-muted-foreground">
                将部分收入捐赠给公益项目，传递校园温暖
              </p>
            </div>

            <div class="space-y-2">
              <label class="text-sm font-medium text-foreground">物品图片</label>
              <div
                class="relative aspect-square rounded-xl overflow-hidden border-2 border-dashed flex items-center justify-center cursor-pointer transition-all hover:border-teal-400"
                :style="{ borderColor: 'var(--border)' }"
                @click="$refs.imageInput.click()"
              >
                <img
                  v-if="productForm.imagePreview"
                  :src="productForm.imagePreview"
                  alt="物品图片"
                  class="w-full h-full object-cover"
                />
                <div v-else class="text-center">
                  <Upload class="w-8 h-8 mx-auto mb-2 text-muted-foreground" />
                  <p class="text-sm text-muted-foreground">点击上传图片</p>
                </div>
                <input
                  ref="imageInput"
                  type="file"
                  accept="image/*"
                  class="hidden"
                  @change="handleImageUpload"
                />
              </div>
            </div>

            <button
              type="submit"
              class="w-full h-11 text-white rounded-xl text-sm font-medium transition-colors"
              :style="{ backgroundColor: 'var(--teal-600)' }"
              :disabled="publishing"
            >
              {{ publishing ? '发布中...' : '发布物品' }}
            </button>
          </form>
        </div>
      </div>
    </div>

    <!-- Product Detail Modal -->
    <div v-if="showDetailModal && selectedProduct" class="fixed inset-0 z-50 flex items-center justify-center">
      <div
        class="absolute inset-0 backdrop-blur-sm"
        :style="{ backgroundColor: 'rgba(45, 42, 38, 0.2)' }"
        @click="showDetailModal = false"
      />
      <div
        class="relative w-full max-w-lg mx-4 rounded-xl shadow-2xl max-h-[90vh] overflow-y-auto"
        :style="{ backgroundColor: 'var(--card)', border: '1px solid var(--border)' }"
      >
        <button
          @click="showDetailModal = false"
          class="absolute top-4 right-4 p-1 rounded-lg text-muted-foreground hover:text-foreground transition-colors"
        >
          <X class="w-5 h-5" />
        </button>
        <div class="p-6">
          <div class="aspect-square rounded-xl overflow-hidden mb-4" :style="{ backgroundColor: 'var(--muted)' }">
            <img
              :src="selectedProduct.image"
              :alt="selectedProduct.title"
              class="w-full h-full object-cover"
            />
          </div>
          <div class="flex items-center gap-2 mb-3 flex-wrap">
            <span
              v-if="selectedProduct.condition"
              class="px-2 py-1 rounded text-xs font-medium text-white"
              :style="{ backgroundColor: 'var(--teal-500)' }"
            >
              {{ getConditionLabel(selectedProduct.condition) }}
            </span>
            <span
              v-if="selectedProduct.category"
              class="px-2 py-1 rounded text-xs font-medium text-white"
              :style="{ backgroundColor: 'var(--teal-600)' }"
            >
              {{ getCategoryLabel(selectedProduct.category) }}
            </span>
            <span
              v-if="selectedProduct.donationPercentage > 0"
              class="px-2 py-1 rounded text-xs font-medium text-white"
              :style="{ backgroundColor: 'var(--amber-500)' }"
            >
              公益 {{ selectedProduct.donationPercentage }}%
            </span>
          </div>
          <h2 class="text-xl font-semibold mb-2 text-foreground">{{ selectedProduct.title }}</h2>
          <p class="text-sm text-muted-foreground mb-4 whitespace-pre-wrap">{{ selectedProduct.description }}</p>
          <div class="flex items-baseline gap-3 mb-4">
            <span class="text-2xl font-semibold" :style="{ color: 'var(--teal-700)' }">
              ¥{{ selectedProduct.price }}
            </span>
            <span v-if="selectedProduct.originalPrice" class="text-sm line-through text-muted-foreground">
              ¥{{ selectedProduct.originalPrice }}
            </span>
          </div>
          <div class="text-xs text-muted-foreground mb-6">
            <p>发布时间：{{ formatDate(selectedProduct.created_at) }}</p>
          </div>
          <div class="flex items-center gap-3 mb-6 pb-4" :style="{ borderBottom: '1px solid var(--border)' }">
            <img
              :src="selectedProduct.publisher.avatar"
              :alt="selectedProduct.publisher.name"
              class="w-10 h-10 rounded-full object-cover"
            />
            <div>
              <p class="text-sm font-medium text-foreground">{{ selectedProduct.publisher.name }}</p>
              <p class="text-xs text-muted-foreground">发布者</p>
            </div>
          </div>
          <div class="flex gap-3">
            <button
              v-if="user && user.id === selectedProduct.seller_id"
              @click="handleEditProduct(selectedProduct)"
              class="flex-1 h-11 rounded-xl text-sm font-medium border transition-all hover:bg-secondary flex items-center justify-center gap-2"
              :style="{ borderColor: 'var(--teal-600)', color: 'var(--teal-600)' }"
            >
              <Edit class="w-4 h-4" />
              编辑
            </button>
            <button
              v-if="user && user.id === selectedProduct.seller_id"
              @click="handleDeleteProduct(selectedProduct)"
              class="flex-1 h-11 rounded-xl text-sm font-medium text-white transition-all hover:opacity-90 flex items-center justify-center gap-2"
              :style="{ backgroundColor: 'var(--destructive)' }"
            >
              <Trash2 class="w-4 h-4" />
              删除
            </button>
            <button
              v-if="user && user.id !== selectedProduct.seller_id"
              class="flex-1 h-11 rounded-xl text-sm font-medium text-white transition-all hover:opacity-90"
              :style="{ backgroundColor: 'var(--teal-600)' }"
            >
              联系卖家
            </button>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { ChevronLeft, Search, Heart, Plus, X, Upload, Edit, Trash2 } from 'lucide-vue-next'
import { supabase } from '@lib/supabase'
import { storageService } from '@lib/storage'

const props = defineProps({
  user: {
    type: Object,
    default: null
  }
})

const categories = [
  { label: "全部", value: "all" },
  { label: "数码", value: "digital" },
  { label: "书籍", value: "books" },
  { label: "服饰", value: "clothes" },
  { label: "电子产品", value: "electronics" },
  { label: "家具", value: "furniture" },
  { label: "日用品", value: "daily" },
  { label: "其它", value: "other" }
]

const products = ref([])

const searchQuery = ref("")
const activeCategory = ref("all")
const showPublishModal = ref(false)
const publishing = ref(false)
const showDetailModal = ref(false)
const selectedProduct = ref(null)
const favoriteIds = ref([])

const loadProducts = async () => {
  try {
    const { data, error } = await supabase
      .from('products')
      .select('*, profiles(username, avatar_url)')
      .order('created_at', { ascending: false })

    if (error) throw error

    products.value = data.map(product => ({
      ...product,
      image: product.image_url || 'https://via.placeholder.com/300?text=No+Image',
      donationPercentage: product.donation_percentage || 0,
      originalPrice: product.original_price,
      publisher: {
        name: product.profiles?.username || (product.profiles?.email ? product.profiles.email.split('@')[0] : '未知用户'),
        avatar: product.profiles?.avatar_url || 'https://api.dicebear.com/7.x/avataaars/svg?seed=default'
      }
    }))
  } catch (error) {
    console.error('Load products error:', error)
  }
}

const loadFavorites = async () => {
  if (!props.user) return

  try {
    const { data, error } = await supabase
      .from('favorites')
      .select('product_id')
      .eq('user_id', props.user.id)

    if (error) throw error

    favoriteIds.value = data.map(f => f.product_id)
  } catch (error) {
    console.error('Load favorites error:', error)
  }
}

onMounted(() => {
  loadProducts()
  loadFavorites()
})

const productForm = ref({
  id: null,
  title: '',
  description: '',
  price: '',
  originalPrice: '',
  category: 'digital',
  condition: 'good',
  donationPercentage: 0,
  image: null,
  imagePreview: ''
})

const getConditionLabel = (condition) => {
  const labels = {
    brand_new: '全新',
    like_new: '几乎全新',
    good: '良好',
    fair: '一般',
    poor: '较差'
  }
  return labels[condition] || condition
}

const getCategoryLabel = (category) => {
  const labels = {
    digital: '数码',
    books: '书籍',
    clothes: '服饰',
    electronics: '电子产品',
    furniture: '家具',
    daily: '日用品',
    other: '其它'
  }
  return labels[category] || category
}

const formatDate = (dateString) => {
  if (!dateString) return ''
  const date = new Date(dateString)
  return date.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const filteredProducts = computed(() => {
  return products.value
    .filter(p => activeCategory.value === "all" || p.category === activeCategory.value)
    .filter(p => p.title.toLowerCase().includes(searchQuery.value.toLowerCase()))
})

const handleImageUpload = (event) => {
  const file = event.target.files[0]
  if (file) {
    productForm.value.image = file
    productForm.value.imagePreview = URL.createObjectURL(file)
  }
}

const handlePublish = async () => {
  if (!props.user) {
    alert('请先登录')
    return
  }

  publishing.value = true

  try {
    let imageUrl = productForm.value.imagePreview
    if (productForm.value.image) {
      const { url, error } = await storageService.uploadProductImage(productForm.value.image)
      if (error) throw error
      imageUrl = url
    }

    const productData = {
      title: productForm.value.title,
      description: productForm.value.description,
      price: parseFloat(productForm.value.price) || 0,
      original_price: parseFloat(productForm.value.originalPrice) || null,
      category: productForm.value.category,
      condition: productForm.value.condition,
      donation_percentage: parseInt(productForm.value.donationPercentage) || 0,
      image_url: imageUrl,
      seller_id: props.user.id,
      likes: 0
    }

    if (productForm.value.id) {
      const { error } = await supabase
        .from('products')
        .update(productData)
        .eq('id', productForm.value.id)

      if (error) throw error

      const index = products.value.findIndex(p => p.id === productForm.value.id)
      if (index !== -1) {
        products.value[index] = {
          ...products.value[index],
          ...productData,
          image: imageUrl,
          donationPercentage: productData.donation_percentage,
          originalPrice: productData.original_price
        }
      }
    } else {
      productData.created_at = new Date().toISOString()
      const { error } = await supabase.from('products').insert([productData])
      if (error) throw error

      products.value.unshift({
        ...productData,
        id: Date.now(),
        image: imageUrl,
        donationPercentage: productData.donation_percentage,
        originalPrice: productData.original_price,
        publisher: {
          name: props.user.username || props.user.email.split('@')[0],
          avatar: props.user.avatar_url
        }
      })
    }

    showPublishModal.value = false
    resetProductForm()
    alert(productForm.value.id ? '商品更新成功！' : '物品发布成功！')
  } catch (error) {
    console.error('Publish error:', error)
    alert('操作失败: ' + error.message)
  } finally {
    publishing.value = false
  }
}

const resetProductForm = () => {
  productForm.value = {
    id: null,
    title: '',
    description: '',
    price: '',
    originalPrice: '',
    category: 'digital',
    condition: 'good',
    donationPercentage: 0,
    image: null,
    imagePreview: ''
  }
}

const isFavorited = (productId) => {
  return favoriteIds.value.includes(productId)
}

const toggleFavorite = async (product) => {
  if (!props.user) {
    return
  }

  try {
    if (isFavorited(product.id)) {
      const { error } = await supabase
        .from('favorites')
        .delete()
        .eq('user_id', props.user.id)
        .eq('product_id', product.id)

      if (error) {
        if (error.message && error.message.includes('duplicate key')) {
          return
        }
        throw error
      }

      favoriteIds.value = favoriteIds.value.filter(id => id !== product.id)
    } else {
      const { error } = await supabase
        .from('favorites')
        .insert([{
          user_id: props.user.id,
          product_id: product.id,
          created_at: new Date().toISOString()
        }])

      if (error) {
        if (error.message && error.message.includes('duplicate key')) {
          favoriteIds.value.push(product.id)
          return
        }
        throw error
      }

      favoriteIds.value.push(product.id)
    }
  } catch (error) {
    console.error('Toggle favorite error:', error)
  }
}

const showProductDetail = (product) => {
  selectedProduct.value = product
  showDetailModal.value = true
}

const handleEditProduct = (product) => {
  showDetailModal.value = false
  showPublishModal.value = true
  productForm.value = {
    title: product.title,
    description: product.description,
    price: product.price,
    originalPrice: product.original_price || '',
    category: product.category,
    condition: product.condition || 'good',
    donationPercentage: product.donation_percentage || 0,
    image: null,
    imagePreview: product.image_url || ''
  }
}

const handleDeleteProduct = async (product) => {
  if (!confirm('确定要删除这个商品吗？')) {
    return
  }

  try {
    const { error } = await supabase
      .from('products')
      .delete()
      .eq('id', product.id)

    if (error) throw error

    products.value = products.value.filter(p => p.id !== product.id)
    showDetailModal.value = false
    alert('商品已删除')
  } catch (error) {
    console.error('Delete error:', error)
    alert('删除失败: ' + error.message)
  }
}
</script>
